spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${USERNAME}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${DB_NAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
springdoc:
  use-management-port: false